
name: Sync Fork

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch: # or manual trigger

env:
    GH_TOKEN: ${{ github.token }}

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Sync
        run: |
          gh auth login --with-token ${{ secrets.PAT }}
          gh repo sync jambrains/graypaper -b main
